import = [
    "~/.config/alacritty/themes/themes/horizon-dark.toml"
]

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/zsh"

[font]
normal = { family = "Fira Code Nerd Font", style = "Regular" }
bold = { family = "Fira Code Nerd Font", style = "Bold" }
italic = { family = "Fira Code Nerd Font", style = "Italic" }
size = 10

[selection]
save_to_clipboard = true

[window]
blur = true
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.95
option_as_alt = "None"
resize_increments = true

