import = [
    "~/.config/alacritty/themes/themes/horizon-dark.toml"
]

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font.normal]
family = "NotoMono"
style = "Regular"

[font]
size = 10

[selection]
save_to_clipboard = true

[window]
blur = true
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.7
option_as_alt = "None"
resize_increments = true
